### ISSUE TITLE
I can't install the extension on VS 2022 Version 17.4.0 Preview 3.0

### ISSUE THREAD

**Issue by StanislavPrusac** [madskristensen/DeveloperNews#18]
**Describe the bug**
I tried to install from the link https://marketplace.visualstudio.com/items?itemName=MadsKristensen.DeveloperNews  and got an error: 
"This extension is not installable on any currently installed products." 
I use Visual Studio (64-bit) - Preview Version 17.4.0 Preview 3.0

**Screenshots:**
![image](https://user-images.githubusercontent.com/1410336/196043319-57c3afe9-8755-4cb7-8577-d520d2be0d5c.png)

**Comment by madskristensen** [comment]
I cannot reproduce the issue. Can you please try with the latest version I just uploaded?

**Comment by madskristensen** [comment]
There was an issue with the vsix installer that was fixed a while ago
