### ISSUE TITLE
Removing C++ Team Blog did not remove C++ news

### ISSUE THREAD

**Issue by SenseiJoe** [madskristensen/DeveloperNews#7]
I unchecked C++ Team Blog, saved and and refreshed the news.  The C++ 20 article was still in the list.

![image](https://user-images.githubusercontent.com/16339587/86639002-3ef5e480-bfa6-11ea-8ea5-c1ab888c9693.png)

**Comment by madskristensen** [comment]
Thanks! The "Featured News" contains news from a broad range of VS related topics - including C++. @DAD713 can you confirm that toggling the checkbox and hitting Save changes the "34 total" at the top left? That way you can see if posts have been added or removed by you unchecking a feed

**Comment by madskristensen** [comment]
"Featured News" is basically highlights only from the various blogs on the list. Each blog has many more posts that don't all make it to the Featured News
